### ISSUE TITLE
per-point transformation matrix Ti

### ISSUE THREAD

**Issue by caiyongqi** [qianlim/POP#14]
Hi. I am confused about the transformation matrix T. The `ri` in Eq(2) is the displacement of the point on posed human body without outfits, why not add `pi` directly? That is: `xi=ri+pi`. Could you explain the T and how to calculate it?

**Comment by qianlim** [comment]
As explained in the paper, the displacements are modeled in the local coordinates. The T_i transforms it from the local coordinates to the global coords. In other words, it can be seen as modeling the displacements in the canonical pose such that the body articulation (i.e. rigid bone transformations) are removed from the displacements so that the network can focus on the non-rigid local deformations of clothing. 
The T_i's are acquired by doing barycentric interpolation using the per-vertex transformation matrices.  See [this issue](https://github.com/qianlim/POP/issues/8) for a bit more detailed explanation. I'll provide the code to this repo no later than June.
